/**
 * MedicationAdviceScreen.js
 * Contributors: Jennifer Lee, Rachel Dijkstra, Lex Janssens, Luuk Deen
 * Description: This is the medication advice screen of the app
 */
import React, { useState, useEffect } from 'react' // import react
import { Text, ScrollView, View, Button } from 'react-native' // import react-native
import { Advices } from '../components/Accordion' // to render the advices
import * as LocalAuthentication from 'expo-local-authentication'
import importedFiles from '../components/ImportedFiles'
import api from '../components/APICall'  // to get api data

/**
 * Prints the medication advice screen, with an accordion of advices with
 * collapsable QR codes and one button to navigate to the about screen
 * When the imported files are not recently imported authentication is required
 * @const MedicationAdviceScreen screen component
 * @param navigation makes navigation between screens possible
 * @return {View} GUI of the medication advice screen
 */
const MedicationAdviceScreen = ( {navigation} ) => {
  // Initialize state for storing advices
  const [advices, setAdvices] = useState([])

  /**
  * Fetches advices from API and stores them in a state
  * @function loadAdvices
  * @param tsitnrs the tsitnrs needed to obtain te relevant advices
  */
  loadAdvices = ( tsitnrs ) => {
    // Fetch advices from API
    api(tsitnrs).then((response) =>{
      setAdvices(response)
    })
  }

  /**
  * Ask for verification from user to see the screen, it uses the same
  * verification as the users phone 
  * @function verification
  */
  verification = async () => {
    let result = await LocalAuthentication.authenticateAsync()
    // keep showing verification screen 
    while(!result.success){
      result = await LocalAuthentication.authenticateAsync()
    }
  }

  // when calling the medication advice screen run one time
  useEffect(() =>{
    // when the files are not just imported
    if(!importedFiles.justImported){
      this.verification()
    }
    importedFiles.justImported = false

    // Obtain advices from API using relevant tsitnrs
    const tsitnrs = [511, 512]  //TODO replace with tsitnrs generated by C-code
    this.loadAdvices(tsitnrs)
  }, [])

  return (
    <ScrollView>
      <Text>U bent nu op het medicatie-advies scherm</Text>
      {/* Render advices*/}
      <Advices advices={advices}></Advices>

      <Button
        // Button to navigate to the about screen
        title="Naar het about scherm"
        onPress={() => navigation.navigate('About')}
      />
    </ScrollView>
  )
}

// export MedicationAdviceScreen function
export default MedicationAdviceScreen
