name: Lint

on:
  push:
  pull_request:
    branches: [ main, Sprint-0, Sprint-1, Sprint-2, Sprint-3, Sprint-4, Sprint-5, Sprint-6 ]

jobs:
  build:
    name: Build repo
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: "./mijnDNAmedicatiepas/package-lock.json"
      
      - name: Clean install NPM
        run: |
          cd mijnDNAmedicatiepas
          npm ci

  lint:

    name: "Runs"
    runs-on: ubuntu-latest

    steps:
    - name: Super-Linter
      uses: github/super-linter@v4.9.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        GOPRIVATE: github.com/ludev-nl/2022-04-mijndnamedicatiepas-app
        
 
